name: leaksan

on: [push,pull_request]
env:
  CI: ON

jobs:
  sanitizer-leak:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - compiler: clang
            build_type: Release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: OpenCV cache
      id: opencv-cache
      uses: actions/cache@v4
      with:
        path: ./libs/opencv_install
        key: ${{ runner.os }}-opencv-cache-v1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Build
      run: python -u build.py --ci --compiler ${{ matrix.compiler}} --build_type ${{ matrix.build_type}} --sanitizer leak

    - name: Test
      run: python -u test.py
