  # infer:
  #     - name: infer install
  #       run: |
  #         sudo apt install curl
  #         VERSION=1.1.0; \
  #         curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux64-v$VERSION.tar.xz" \
  #         | sudo tar -C /opt -xJ && \
  #         sudo ln -s "/opt/infer-linux64-v$VERSION/bin/infer" /usr/local/bin/infer

  #     - name: infer run
  #       continue-on-error: true
  #       run: infer run --compilation-database build/compile_commands.json --keep-going
