#pragma once

// STL
#include <iostream>
#include <stdio.h>
#include <conio.h>
#include <fstream>
#include <stdint.h>
#include <string>
#include <chrono>
#include <numeric>
#include <time.h>
#include <math.h>
#include <filesystem>
#include <queue>
#include <functional>
#include <vector>
#include <complex>
#include <tuple>
#include <thread>
#include <memory>
#include <regex>
#include <ctime>
#include <limits>
#include <random>
#include <algorithm>
#include <mutex>
#include <map>
#include <unordered_map>
// Qt
#include <QtWidgets>
#include <QtWidgets>
#include <QtWidgets/QApplication>
#include <QPixmap>
#include <QWidget>
#include <QCloseEvent>
// OpenMP
#include <omp.h>
// OpenCV
#include <opencv2/opencv.hpp>
#include <opencv2/core.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/features2d.hpp>
//#include <opencv2/xfeatures2d.hpp>
//#include <opencv2/cudaarithm.hpp>
// QCustomPlot
#include "Plot/qcustomplot.h"
// fmt
#include <fmt/format.h>
#include <fmt/ostream.h>
// custom
#include "Log/Logger.h"
#include "Log/LogFunction.h"
#include "Core/constants.h"
#include "Core/functionsBaseSTL.h"
#include "Core/functionsBaseCV.h"
#include "Plot/Plot1D.h"
#include "Plot/Plot2D.h"
#include "Draw/showsave.h"
#include "Draw/draw.h"
#include "Draw/crop.h"
