name: build-windows

on: [push,pull_request]
env:
  CI: ON
  build-jobs: 8

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build-type: [Debug]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Libs cache
      id: libs-cache
      uses: actions/cache@v3
      with:
        path: |
          libs/opencv
          libs/libzmq
        key: ${{ runner.os }}-${{ matrix.build-type }}-libs-cache-v1

    - name: OpenCV install from cache
      if: steps.libs-cache.outputs.cache-hit == 'true'
      run: cd libs/opencv && cmake install build

    - name: OpenCV install from source
      if: steps.libs-cache.outputs.cache-hit != 'true'
      run: |
        cd libs
        git clone https://github.com/opencv/opencv.git --branch 4.x --single-branch --depth 1
        cd opencv
        git clone https://github.com/opencv/opencv_contrib.git --branch 4.x --single-branch --depth 1
        mkdir build
        cmake -B build -D CMAKE_BUILD_TYPE=${{ matrix.build-type }} -D CMAKE_INSTALL_PREFIX=install -DOPENCV_ENABLE_NONFREE=ON -DOPENCV_EXTRA_MODULES_PATH="opencv_contrib/modules" -DBUILD_TESTS=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_apps=OFF
        cmake --build build --config ${{ matrix.build-type }} -j${{ env.build-jobs }}
        cmake install build

    - name: ZeroMQ install from cache
      if: steps.libs-cache.outputs.cache-hit == 'true'
      run: cd libs/libzmq && cmake install build

    - name: ZeroMQ install from source
      if: steps.libs-cache.outputs.cache-hit != 'true'
      run: |
        cd libs
        git clone https://github.com/zeromq/libzmq.git --single-branch --depth 1
        cd libzmq
        mkdir build
        cmake -B build -D CMAKE_BUILD_TYPE=${{ matrix.build-type }} -D CMAKE_INSTALL_PREFIX=install
        cmake --build build --config ${{ matrix.build-type }} -j${{ env.build-jobs }}
        cmake install build

    - name: Build
      run: |
        mkdir build
        cmake -B build -D CMAKE_BUILD_TYPE=${{ matrix.build-type }}
        cmake --build build --config ${{ matrix.build-type }} -j${{ env.build-jobs }}

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ runner.os }}-${{ matrix.build-type }}
        path: build

