name: build

on: [push,pull_request]
env:
  CI: ON

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
            generator: ninja
            build_type: Release

          # - os: ubuntu-latest
          #   compiler: clang
          #   generator: ninja
          #   build_type: Release

          # - os: windows-latest
          #   compiler: msvc
          #   build_type: Release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Libs cache
      id: libs-cache
      uses: actions/cache@v3
      with:
        path: ./libs
        key: ${{ runner.os }}-libs-cache-v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Build
      run: python3 -u build.py




