name: build-windows

on: [push,pull_request]
env:
  CI: ON

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build-type: [Debug]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Libs cache
      id: libs-cache
      uses: actions/cache@v3
      with:
        path: libs/opencv-install
        key: ${{ runner.os }}-libs-cache-v1

    - name: OpenCV install from cache
      if: steps.libs-cache.outputs.cache-hit == 'true'
      run: cd libs/opencv && cmake --install build --prefix ../../build

    - name: OpenCV install from source
      if: steps.libs-cache.outputs.cache-hit != 'true'
      run: |
        cd libs/opencv
        mkdir build
        cmake -B build -D CMAKE_BUILD_TYPE=Release -DOPENCV_EXTRA_MODULES_PATH="../opencv_contrib/modules" -DOPENCV_ENABLE_NONFREE=ON -DBUILD_TESTS=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_apps=OFF
        cmake --build build --config Release
        cmake --install build --prefix ../../build

    - name: Build
      run: |
        mkdir build
        cmake -B build -D CMAKE_BUILD_TYPE=${{ matrix.build-type }}
        echo "${{ github.workspace }}/build/x64/vc17/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        cmake --build build --config ${{ matrix.build-type }}

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ runner.os }}-${{ matrix.build-type }}
        path: build

