name: build-linux

on: [push,pull_request]
env:
  CI: ON
  build-jobs: 8

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug, Release]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Install CMake + Ninja + OpenGL
      run: |
        sudo apt-get install -y cmake
        sudo apt install ninja-build
        sudo apt install libglu1-mesa-dev mesa-common-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev

    - name: Install GCC 13
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install -y gcc-13 g++-13
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 90 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 90

    - name: OpenCV cache
      id: libs-cache
      uses: actions/cache@v3
      with:
        path: |
          libs/opencv
          libs/libzmq
        key: ${{ runner.os }}-${{ matrix.build-type }}-libs-cache-v1

    - name: OpenCV install from cache
      if: steps.libs-cache.outputs.cache-hit == 'true'
      run: cd libs/opencv && cmake install build

    - name: OpenCV install from source
      if: steps.libs-cache.outputs.cache-hit != 'true'
      run: |
        cd libs
        git clone https://github.com/opencv/opencv.git --branch 4.x --single-branch --depth 1
        cd opencv
        git clone https://github.com/opencv/opencv_contrib.git --branch 4.x --single-branch --depth 1
        mkdir build
        cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=${{ matrix.build-type }} -D CMAKE_INSTALL_PREFIX=install -DOPENCV_ENABLE_NONFREE=ON -DOPENCV_EXTRA_MODULES_PATH="opencv_contrib/modules" -DBUILD_TESTS=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_apps=OFF
        cmake --build build --config ${{ matrix.build-type }} -j${{ env.build-jobs }}
        cmake install build

    - name: ZeroMQ install from cache
      if: steps.libs-cache.outputs.cache-hit == 'true'
      run: cd libs/libzmq && cmake install build

    - name: ZeroMQ install from source
      if: steps.libs-cache.outputs.cache-hit != 'true'
      run: |
        cd libs
        git clone https://github.com/zeromq/libzmq.git --single-branch --depth 1
        cd libzmq
        mkdir build
        cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=${{ matrix.build-type }} -D CMAKE_INSTALL_PREFIX=install
        cmake --build build --config ${{ matrix.build-type }} -j${{ env.build-jobs }}
        cmake install build

    - name: Build
      run: |
        mkdir build
        cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=${{ matrix.build-type }}
        cmake --build build --config ${{ matrix.build-type }} -j${{ env.build-jobs }}

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ runner.os }}-${{ matrix.build-type }}
        path: build

