name: build/test

on: [push,pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: gcc install
      run: |
        sudo apt install gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
        sudo update-alternatives --set gcc /usr/bin/gcc-11

    - name: ninja install
      run: sudo apt-get install -y ninja-build

    - name: python install
      uses: actions/setup-python@v2

    - name: opencv cache
      id: opencv-cache
      uses: actions/cache@v2
      with:
        path: ./opencv-install
        key: ${{runner.os}}-opencv-cache

    - name: opencv install
      uses: rayandrews/with-opencv-action@v1
      with:
        opencv-version: '4.5.1'
        dir: ./opencv-install
        cached: ${{steps.opencv-cache.outputs.cache-hit}}

    - name: qt cache
      id: qt-cache
      uses: actions/cache@v2
      with:
        path: ./qt
        key: ${{runner.os}}-qt-cache

    - name: qt install
      uses: jurplel/install-qt-action@v2
      with:
        version: "5.12.2"
        dir: "./qt"
        install-deps: true
        setup-python: false
        cached: ${{steps.qt-cache.outputs.cache-hit}}

    - name: cmake configure
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B '${{github.workspace}}'/build -G "Ninja" -DCI=ON

    - name: cmake build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: cmake test
      run: (cd ${{github.workspace}}/build; ctest -C ${{env.BUILD_TYPE}})

    - name: run test
      run: (cd ${{github.workspace}}/build; ./shenanigans_test)

