name: build-linux-python

on: [push,pull_request]
env:
  CI: ON

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Libs cache
      id: libs-cache
      uses: actions/cache@v3
      with:
        path: ./libs
        key: ${{ runner.os }}-libs-cache-v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Build
      run: python3 -u build.py




