name: cppcheck

on: [push,pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cppcheck run
        run: sudo python -m script.ci.cppcheck
