name: cppcheck

on: [push,pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cppcheck install
        run: sudo apt install -y cppcheck

      - name: Cppcheck run
        run: cppcheck --enable=all --suppressions-list=.cppcheck-suppressions --inconclusive --error-exitcode=1 src/ apps/
