name: cppcheck

on: [push,pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cppcheck install
        run: sudo apt-get install -y cppcheck

      - name: Cppcheck run #--project=build/compile_commands.json
        run: |
          cppcheck --enable=all --suppressions-list=.cppcheck-suppressions --inconclusive --error-exitcode=0 src/ 2> cppcheck-result.txt
          cat cppcheck-result.txt
