name: cppcheck

on: [push,pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2

    - name: cppcheck install
      run: sudo apt-get install -y cppcheck

    - name: cppcheck run
      run: cppcheck --enable=all -I external/ --error-exitcode=0 src/
