name: cpplint
on: [push,pull_request]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2

    - name: python install
      uses: actions/setup-python@v2

    - name: cpplint install
      uses: BSFishy/pip-action@v1
      with:
        packages: cpplint

    - name: cpplint run
      run: find src/ -name '*.h' -name '*.hpp' -o -name '*.cpp' | xargs cpplint
