name: flawfinder

on: [push,pull_request]

jobs:
  flawfinder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Flawfinder
        run: python -m script.ci.flawfinder
