name: infer

on: [push, pull_request]

env:
  CI: ON

jobs:
  infer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - compiler: clang
            build_type: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: OpenCV cache
        id: opencv-cache
        uses: actions/cache@v4
        with:
          path: ./libs/opencv_install
          key: ${{ runner.os }}-opencv-cache-v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build
        run: python -u build.py --ci --compiler ${{ matrix.compiler }} --build_type ${{ matrix.build_type }}

      - name: Download Infer
        run: |
          VERSION=1.2.0  # Set the desired version of Infer
          curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux-x86_64-v$VERSION.tar.xz" \
          | tar -C /opt -xJ && \
          sudo ln -s "/opt/infer-linux-x86_64-v$VERSION/bin/infer" /usr/local/bin/infer

      - name: Run Infer
        run: |
          cd build  # Change to the build directory
          infer run -- make
