name: infer

on: [push, pull_request]

jobs:
  infer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: OpenCV cache
        id: opencv-cache
        uses: actions/cache@v4
        with:
          path: ./libs/opencv_install
          key: ${{ runner.os }}-opencv-cache-v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang make git cmake

      - name: Download Infer
        run: |
          wget https://github.com/facebook/infer/releases/download/v1.2.0/infer-linux-x86_64-v1.2.0.tar.xz
          tar -xf infer-linux-x86_64-v1.2.0.tar.xz
          sudo mv infer-* /usr/local/bin/infer  # Move to /usr/local/bin for easier access
          sudo chmod +x /usr/local/bin/infer/infer  # Ensure the infer binary is executable

      - name: Build
        run: python -u build.py --ci --compiler clang --build_type Release

      - name: Run Infer
        run: |
          cd build
          /usr/local/bin/infer/infer run --make-command="make" --output=../infer_out

      - name: Generate Infer Report
        run: |
          cd /usr/local/bin/infer  # Navigate to the infer directory
          infer report --no-filter --results-dir=../infer_out
