name: lint

on: [push,pull_request]

jobs:
  # clang-tidy:
  #   runs-on: ubuntu-latest
  #   continue-on-error: true
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Install clang-tidy
  #     run: sudo apt-get install -y clang-tidy

  #   - name: Run clang-tidy
  #     run: find src/ -name '*.h' -name '*.hpp' -o -name '*.cpp' | xargs clang-tidy --format-style=file

  cppcheck:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2

    - name: Install cppcheck
      run: sudo apt-get install cppcheck

    - name: Run cppcheck
      run: cppcheck --enable=all -I external/ --error-exitcode=0 --verbose src/

  cpplint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
    - uses: BSFishy/pip-action@v1
      with:
        packages: cpplint

    - name: Run cpplint
      run: find src/ -name '*.h' -name '*.hpp' -o -name '*.cpp' | xargs cpplint
