name: lint

on: [push,pull_request]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2

    - name: Install clang-tidy
      run: sudo apt-get install -y clang-tidy

    - name: Run clang-tidy
      working-directory: ${{github.workspace}}
      run: find src/ -name '*.h' -o -name '*.cpp' | xargs clang-tidy --format-style=file

  cppcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install cppcheck
      run: sudo apt-get install cppcheck

    - name: Run cppcheck
      working-directory: ${{github.workspace}}
      run: | 
        cppcheck --std=c++20 --enable=all -I external/ --report-progress --output-file=cppcheck_report.txt src/
        cat cppcheck_report.txt
  
  cpplint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
    - uses: BSFishy/pip-action@v1
      with:
        packages: cpplint

    - name: Run cpplint
      run: find src/ -name '*.h' -o -name '*.cpp' | xargs cpplint --quiet
