name: pylint

on: [push,pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pylint run
        run: sudo python -m script.ci.pylint
