name: ruff

on: [push,pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ruff run
        run: sudo python -m script.ci.ruff
