name: test

on:
  workflow_run:
    workflows: ["build-linux"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug, Release]

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-${{ runner.os }}-${{ matrix.build-type }}
        path: build

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
