name: test

on: [push,pull_request]

jobs:
  test:
     runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup linux
        run: sudo chmod 755 script/linux/setup_linux.sh && ./script/linux/setup_linux.sh
    
      - name: OpenCV cache
        id: opencv-cache
        uses: actions/cache@v3
        with:
          path: ./opencv
          key: ${{runner.os}}-opencv-cache

      - name: OpenCV install from cache
        if: steps.opencv-cache.outputs.cache-hit == 'true'
        run: cd opencv/build && sudo ninja install

      - name: OpenCV install from source
        if: steps.opencv-cache.outputs.cache-hit != 'true'
        run: sudo chmod 755 script/linux/setup_opencv.sh && ./script/linux/setup_opencv.sh

      - name: CMake configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -B ${{github.workspace}}/build -G Ninja

      - name: CMake build
        run: cmake --build ${{github.workspace}}/build --config Release -j 6

      - name: Execute test
        working-directory: ${{github.workspace}}/build
        run: ./shenanigans_test

      - name: CMake test
        working-directory: ${{github.workspace}}/build
        run: ctest --rerun-failed --output-on-failure
